blank_issues_enabled: false

contact_links:
  - name: ðŸ’¬ Community Discussion
    url: https://github.com/MrTimeey/everybodycodes-data/discussions
    about: Ask questions and share ideas with other contributors.
